show current time and date on the clock tab.
YaroslavP1995/SimpleClock pull request #4
Opened 2019-09-02 20:30 UTC by YaroslavP1995

Show Current time and date on the clock tab. PR my task .

2019-09-02 20:42 UTC, Artem-Zelinka requested changes
Remove all unnecessary changes. Remove 1 of your layouts. Move all values to dimens/colors/strings. Fix first and second views placement

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:timeZone="GMT+0300"
Why your timezone is here? You don't need to hardcode it. It need to take time from your system!

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:timeZone="GMT+0300"
Why your timezone is here? You don't need to hardcode it. It need to take time from your system!

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:textSize="33sp"
move to dimens

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:textColor="#29b6f6"
move to colors

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:format24Hour="HH:mm:ss"
Move to strings

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:format12Hour="h:mm:ss"
Move to strings

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:format24Hour="“EEE, d MMM”"
Move to strings

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:format12Hour="“EEE, d MMM”"
Move to strings

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:textColor="#786543"
Move to colors

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:textSize="16sp"
Move to dimens

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +<?xml version="1.0" encoding="utf-8"?>
Why you have 2 different clock_fragment layouts? Remove other one, this move to layout folder

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/java/com/pysiak/simple/clock/ui/clock/ClockFragment.java
>  import android.view.LayoutInflater;
No any real change in this class. So remove all new imports and new lines

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:layout_alignParentTop="true"
You first clock need to be at the top of screen and centered horizontally. AlignParentTop is incorrect

2019-09-02 20:42 UTC, iu18054 commented on app/src/main/res/layout-v17/clock_fragment.xml
> +            android:layout_centerInParent="true"
You second view need to be after the first view and need to be centered horizontally. AlignParentTop is incorrect

2019-09-03 14:48 UTC, YaroslavP1995 commented
Please rewiew my change .

2019-09-03 15:26 UTC, Artem-Zelinka requested changes
Don't use anything you don't know how to use and for what reason... Don't change anything without any reason

2019-09-03 15:26 UTC, iu18054 commented on app/src/main/res/layout/clock_fragment.xml
> +            tools:targetApi="jelly_bean_mr1"/>
What is this? Why you need this?

2019-09-03 15:26 UTC, iu18054 commented on app/src/main/res/layout/clock_fragment.xml
> +            tools:targetApi="jelly_bean_mr1"/>
What is this? Why you need this?

2019-09-03 15:26 UTC, iu18054 commented on app/src/main/res/values/styles.xml
> +        <item name="colorPrimary">@color/secondaryViewColor</item>
Why you change it in style?

2019-09-03 16:37 UTC, Artem-Zelinka approved these changes

2019-09-03 16:38 UTC, YaroslavP1995 commented
Turned the styles back

2019-09-03 16:40 UTC, merged